version: "3"
services:
  app:
    hostname: "app"
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - MYSQLDB_USER=$MYSQLDB_USER
      - MYSQLDB_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQLDB_DATABASE=$MYSQLDB_DATABASE
      - MYSQLDB_LOCAL_PORT=$MYSQLDB_DOCKER_PORT
    volumes:
      - ./server/src:/app/src
    ports:
      - "8080:8080"
    networks:
      - backbone
  db:
    image: mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - worlds-2022:/var/lib/mysql
    networks:
      - backbone
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - backbone

volumes:
  worlds-2022:
    external: true

networks:
  backbone:
    driver: bridge
